In [1]:
#part1 #importing

import pandas as pd
needed_data = pd.read_csv(r"/Users/david/Desktop/fish.csv")
print(needed_data)

    Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]


In [2]:
#part1 #a
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()
needed_data_encoded = ordinal_encoder.fit_transform(needed_data)

In [3]:
#part1 #a #continuation
from sklearn.preprocessing import OneHotEncoder
cat_encoder = OneHotEncoder()
needed_data_1hot = cat_encoder.fit_transform(needed_data)
needed_data_1hot.toarray()

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [4]:
#part1 #b
columns = needed_data[['Length1','Length2','Length3','Height','Width']].values.astype(float)

columns

normalized = (columns-columns.min())/(columns.max()-columns.min())

normalized

array([[0.3308679 , 0.36372707, 0.43243259, 0.1564156 , 0.04439572],
       [0.34281669, 0.37716945, 0.45035578, 0.17075415, 0.04866144],
       [0.34132309, 0.38015665, 0.44886218, 0.16922769, 0.05449394],
       [0.37716945, 0.41749661, 0.48470854, 0.17448814, 0.05090034],
       [0.38015665, 0.41749661, 0.49217653, 0.17021645, 0.06103441],
       [0.38463744, 0.4279518 , 0.50263172, 0.1875183 , 0.05794863],
       [0.38463744, 0.4279518 , 0.49964452, 0.19613785, 0.06319266],
       [0.39658623, 0.43243259, 0.50711252, 0.17359198, 0.05440283],
       [0.39658623, 0.43243259, 0.50860611, 0.19353003, 0.05669998],
       [0.41002862, 0.44288778, 0.5250357 , 0.19684134, 0.05842658],
       [0.40853502, 0.44736858, 0.5250357 , 0.19738202, 0.06058931],
       [0.41301581, 0.44736858, 0.5250357 , 0.19900407, 0.05626385],
       [0.41899021, 0.45483657, 0.52802289, 0.18986026, 0.04959344],
       [0.4249646 , 0.46230456, 0.54146528, 0.19215592, 0.06012032],
       [0.423471  , 0.46230456, 0.

In [5]:
#part3 #a
#randomising the order of the rows
import pandas as pd
import numpy as np

shuffled_data = pd.DataFrame(needed_data)

shuffled_data = shuffled_data.sample(frac=1)

print(shuffled_data)





    Species  Weight  Length1  Length2  Length3   Height   Width
33    Bream   975.0     37.4     41.0     45.9  18.6354  6.7473
37    Roach    78.0     17.5     18.8     21.2   5.5756  2.9044
16    Bream   700.0     30.4     33.0     38.3  14.8604  5.2854
140    Pike   950.0     48.3     51.7     55.1   8.9262  6.1712
109   Perch   514.0     30.5     32.8     34.0  10.0300  6.0180
..      ...     ...      ...      ...      ...      ...     ...
112   Perch   685.0     34.0     36.5     39.0  10.8810  6.8640
14    Bream   600.0     29.4     32.0     37.2  14.9544  5.1708
46    Roach   140.0     21.0     22.5     25.0   6.5500  3.3250
128    Pike   200.0     30.0     32.3     34.8   5.5680  3.3756
62   Parkki    60.0     14.3     15.5     17.4   6.5772  2.3142

[159 rows x 7 columns]


In [6]:
#part3 #a #continuation

# from sklearn.datasets import shuffled_data
shuffled_data
df = pd.DataFrame(shuffled_data, columns = ['Species','Weight','Length1','Length2','Length3','Height','Width'])


# Selecting the features
features = ['Weight','Length1','Length2','Length3','Height', 'Width']
x = df[features]

# Target Variable
y = df['Species']


from sklearn.model_selection import train_test_split
#Splitting the dataset into the training and test set
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.40, random_state = 25 )

In [7]:
#part3 #b

from sklearn.linear_model import SGDClassifier

# Fitting SGD Classifier to the Training set
model = SGDClassifier(loss="hinge", alpha=0.01, max_iter=200)
model.fit(x_train, y_train)

# Predicting the results
y_pred = model.predict(x_test)

In [11]:
#part3 #b #continuation

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import precision_score

# Confusion matrix
print("Confusion Matrix")
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

# Classification Report
print("\nClassification Report")
report = classification_report(y_test, y_pred)
print(report)

# Accuracy of the model
accuracy = accuracy_score(y_test, y_pred)

print('SGD Classifier Accuracy of the model: {:.2f}%'.format(accuracy*100))




Confusion Matrix
[[ 0  0  0  0 20  0  0]
 [ 0  0  0  0  4  0  0]
 [ 0  0  0  0 15  0  0]
 [ 0  0  0  0  4  0  0]
 [ 0  0  0  0 10  0  0]
 [ 0  0  0  0  7  0  0]
 [ 0  0  0  0  4  0  0]]

Classification Report
              precision    recall  f1-score   support

       Bream       0.00      0.00      0.00        20
      Parkki       0.00      0.00      0.00         4
       Perch       0.00      0.00      0.00        15
        Pike       0.00      0.00      0.00         4
       Roach       0.16      1.00      0.27        10
       Smelt       0.00      0.00      0.00         7
   Whitefish       0.00      0.00      0.00         4

    accuracy                           0.16        64
   macro avg       0.02      0.14      0.04        64
weighted avg       0.02      0.16      0.04        64

SGD Classifier Accuracy of the model: 15.62%


/Users/david/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/david/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/david/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [8]:
#part3 #c

from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

x, y = make_classification(n_samples=160, n_features=12, 
                            n_classes=4, n_clusters_per_class=1)

xtrain, xtest, ytrain, ytest=train_test_split(x, y, test_size=0.40)

knc = KNeighborsClassifier(n_neighbors=50)
print(knc)

knc.fit(xtrain, ytrain)

score = knc.score(xtrain, ytrain)
print("Training score: ", score)

ypred = knc.predict(xtest)
cm = confusion_matrix(ytest, ypred)
print(cm)

cr = classification_report(ytest, ypred)
print(cr)

KNeighborsClassifier(n_neighbors=50)
Training score:  0.75
[[ 8  1  6  2]
 [ 2  9  0  7]
 [ 0  0 15  1]
 [ 0  0  0 13]]
              precision    recall  f1-score   support

           0       0.80      0.47      0.59        17
           1       0.90      0.50      0.64        18
           2       0.71      0.94      0.81        16
           3       0.57      1.00      0.72        13

    accuracy                           0.70        64
   macro avg       0.74      0.73      0.69        64
weighted avg       0.76      0.70      0.69        64



In [9]:
#par2 #a
# Selecting the features
features = ['Species','Length1','Length2','Length3','Height', 'Width']
a = df[features]
# Target Variable
b = df['Weight']

a = shuffled_data.iloc[:,:-1].values
b=shuffled_data.iloc[:,:-1].values

from sklearn.model_selection import train_test_split
# Splitting the dataset into the training and test set
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size = 0.40, random_state = 25 )

In [10]:
#part2 #b

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
import numpy as np


np.set_printoptions(suppress=True)
labelencoder_exp = LabelEncoder()
shuffled_data['Species']=labelencoder_exp.fit_transform(shuffled_data['Species'])

ct = ColumnTransformer([("Species", OneHotEncoder(), [0])], remainder = 'passthrough')
shuffled_data_encoded = ct.fit_transform(shuffled_data)


In [11]:
#part2 #b #continuation

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
import numpy as np

from sklearn.linear_model import LinearRegression

labelencoder_exp = LabelEncoder()
shuffled_data['Species']=labelencoder_exp.fit_transform(shuffled_data['Species'])

ct = ColumnTransformer([("Species", OneHotEncoder(), [0])], remainder = 'passthrough')
shuffled_data_encoded = ct.fit_transform(shuffled_data)

reg=LinearRegression()
#random_fish_df_encoded = random_fish_df_encoded.drop('Weight',axis='columns')
a_train, a_test = train_test_split(shuffled_data_encoded, test_size=0.4)
b_train, b_test = train_test_split(needed_data.Weight, test_size=0.4)
a=shuffled_data_encoded
y=needed_data.Weight

reg_pred = reg.fit(a_train,b_train)


In [12]:
#part2 #b #continuation
print(reg.coef_)


[ 618.6379684   238.1141262  -282.18826239   95.76167571  -81.82807631
 -427.93656157 -160.56087003    0.60002611  238.07035651  -36.63658342
 -218.34501556  -46.50031126  216.39072746]


In [13]:
#part2 #b #continuation
b_pred = reg.predict(a_test)

from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(b_test, b_pred))
print('Mean Squared Error:', metrics.mean_squared_error(b_test, b_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(b_test, b_pred)))

Mean Absolute Error: 314.0158316810041
Mean Squared Error: 149787.22199150134
Root Mean Squared Error: 387.0235419086303


In [ ]:
#part2 #c 
#polynomial regression

from sklearn.preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures(degree=1, include_bias=False)
a_train_poly = poly_features.fit_transform(a_train)
a_test_poly = poly_features.fit_transform(a_test)


In [29]:
#part2 #c #continuation

poly_model =LinearRegression()
#print(x_train_poly)
#print(type(y_train))
b_train = b_train.to_numpy(dtype='float')
b_train = b_train.reshape(-1,1)
b_test = b_test.to_numpy(dtype='float')
b_test = b_test.reshape(-1,1)
#print(y_train)
#y_train = y_train.to_numpy(dtype='float')

poly_model.fit(a_train_poly, b_train)


LinearRegression()

In [30]:
poly_model.coef_

array([[ 618.6379684 ,  238.1141262 , -282.18826239,   95.76167571,
         -81.82807631, -427.93656157, -160.56087003,    0.60002611,
         238.07035651,  -36.63658342, -218.34501556,  -46.50031126,
         216.39072746]])

In [31]:
poly_model.intercept_

array([1236.75488664])

In [32]:
poly_train_pred = poly_model.predict(a_train_poly)
poly_test_pred = poly_model.predict(a_test_poly)


In [33]:
print('Root Mean Squared training Error:', np.sqrt(metrics.mean_squared_error(b_train, poly_train_pred)))
print('Root Mean Squared test Error:', np.sqrt(metrics.mean_squared_error(b_test, poly_test_pred)))

Root Mean Squared training Error: 316.39302132490855
Root Mean Squared test Error: 387.0235419086303
